### PR TITLE
Mirgate to Silex 2.0

### PR DESCRIPTION
**Pull request by sanderua**
For backward compatibility before merging please create tag v1.3 or something like this

### CODE REVIEW

**Comment by dadaxr** [comment]
Thanks @sanderua exactly what I need :)

**Comment by infostreams** [comment]
Please just accept this pull request! I want to use your code but I am on Silex 2.0... At the very least accept it in a different branch or version?

**Comment by dadaxr** [comment]
And it could be listed in [Silex 2.X provider](https://github.com/silexphp/Silex/wiki/Third-Party-ServiceProviders-for-Silex-2.x#templating)

as the current master is already listed in the same wiki but for [Silex 1.X provider](https://github.com/silexphp/Silex/wiki/Third-Party-ServiceProviders-Silex-1.x#templating)

**Comment by dadaxr** [comment]
Also : I currently use the @sanderua proposal in my silex 2 project, and it's working perfectly, so you can just merge in a new branch :)

**Comment by infostreams** [comment]
Just for reference, you can update your `composer.json` to use @sanderua 's version by adjusting it to look something like this:

```
{
    "require": {
        "silex/silex": "~2.0",
        "litek/silex-php-engine": "dev-silex2.0"
    },
    "repositories": [
        {
            "url": "https://github.com/sanderua/silex-php-engine.git",
            "type": "git"
        }
    ]
}
```

**Comment by litek** [comment]
Sorry, this totally fell off my radar. Thanks!

**Comment by dadaxr** [comment]
Thx :) 

FYI, I updated the silex 2 wiki : 

https://github.com/silexphp/Silex/wiki/Third-Party-ServiceProviders-for-Silex-2.x#templating

**Pull request merged**
